name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      # Install Linux dependencies
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev adb

      # Install Python build tools
      - name: Install Python build tools
        run: |
          pip install --upgrade pip setuptools wheel

      # Install Buildozer
      - name: Install Buildozer
        run: pip install buildozer

      # Validate Flutter environment
      - name: Run Flutter doctor
        run: flutter doctor

      # Build APK
      - name: Build APK
        run: |
          buildozer android debug

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
